config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 root 'users#index'
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :create, :new] do
    end
  end

    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, foreign_key: 'post_id'
  has_many :comments, foreign_key: 'post_id'
  belongs_to :author, class_name: 'User', dependent: :destroy, foreign_key: 'author_id'
  after_save :update_posts_counter

  validates :title, presence: true, length: { in: 1..250 }

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def last_five_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def last_three_posts
    posts.last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @user.comments.new(handle_params)
    @comment.author_id = @user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to user_post_path(@user.id, @post)
    else
      render new, locals: { comment: @comment }
    end
  end

  def handle_params
    params.require(:comments).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @likes = Like.new(like_params)
    if @likes.save
      redirect_to user_post_path(@user, @post)
    else
      flash.now[:error] = 'comment not added'
      @likes.errors.full_messages.join(', ')
    end
  end

  private

  def like_params
    { author: current_user, post_id: params.require(:post_id) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(comments: [:user]).where(user: @user)
  end

  def new
    render :new, locals: { author: current_user, post: Post.new }
  end

  def create
    respond_to do |format|
      format.html do
        @user = current_user
        @post = @user.posts.new(helper_params)
        @post.author_id = current_user.id
        if @post.save
          redirect_to user_posts_path(@user)
        else
          render :new, locals: { author: current_user, post: @post }
        end
      end
    end
  end

  def show
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id)
    @post = Post.find(params[:id])
  end

  private

  def helper_params
    params.require(:post).permit(:title, :text).merge(author_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.where(author_id: @user.id)
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: @comment, url: post_comments_path(@user, @post), method: :post, local: true, scope: :comments do |f|%>
    <div>
      <%= f.label :text%>
      <%= f.text_field :text%>
    </div>
    <%= f.submit "Comment" %>
  <% end %>

app/views/comments/new.html.erb
<h2 id="new_h21">Comment Here</h2>
<div id="new_comments_form_cont">
  <%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div>
      <% if user_signed_in?%>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "my_button" %>
      <% else %>
      <div>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
  <%= form_with model: @likes, url: post_likes_path(@user, @post), method: :post, scope: :likes do |f| %>
    <%= f.submit "like post"%>
  <% end %>

app/views/posts/_form.html.erb
<%= form_with url: user_posts_path(author), method: :post, scope: :post do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :text %>
      <%= f.text_field :text %>
    </div>
     <div>
    <%= f.submit 'Post'%>
    </div>
  <% end %>

app/views/posts/index.htm.erb
<h1>Hello new Post</h1>

app/views/posts/index.html.erb
<div id="posts_container">
  <div id="user_container">
      <img id="user_img" src="<%= @user.photo %>" alt="user profile">
      <div id="container_container_div">
        <h3><%= @user.name %></h3>
        <p>Number of posts: <%= @user.posts_counter %></p>
      </div>
    </div>
    <% @posts.each do |post|%>
    <div id="user_posts">
    <%= link_to user_post_path(@user, post) do %>
      <h3>Post #<%= post.id %>
      Title: <%= post.title %>
      </h3>
      <% end %>
      <p><%= post.text %></p>
      <h4>Comments <%= post.comments_counter %> likes: <%= post.likes_counter %></h4>
    </div>
    <% post.last_five_comments.each do |comment| %>
        <div id="comments">
        <%= @user.name%>: <%= comment.text%>
        </div>
    <% end %>
  <% end %>
  <div id="button_container">
    <button id="pagination_button">Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<div>
<%= render 'form', author:, post:%>
</div>

app/views/posts/show.html.erb
<div id="post_container">
  <div id="post_details">
  <div id="post_header">
    <h3>Post #<%= @post.id%> by <%=@user.name%></h3>
    <h5>Comments:<%= render layout: 'shared/tag' do%>
      <%= @post.comments_counter%> 
    <% end %> <span>
    Likes:<%= render layout: 'shared/tag' do%>
      <%= @post.likes_counter%>
    <% end %>
    </span>
  </div>
  <p><%= @post.text %></p>
  <%= render partial: 'likes/form', locals: {post: @post} %>
  <%= render partial: 'comments/form', locals: {post: @post} %>
  </div>
  <% @comments=Comment.where(post_id:@post.id) %>
  <div id="users_comment">
    <% @comments.each do |comment| %>
      <p><%=@user.name%>: Comment: <%= comment.text %></p>
    <% end %>
  </div>
</div>

app/views/shared/_tag.html.erb
<div>
<%= yield%>
</div>

app/views/users/_user.html.erb
<div id="user_container">
    <img id="user_img" src="<%= user.photo %>" alt="user profile">
      <div id="container_container_div">
        <h3><%= link_to user.name, "/users/#{user.id}"%></h3>
        <p>Number of posts: <%= user.posts_counter %></p>
      </div>
</div>

app/views/users/index.html.erb
<div id="user_list"> 
  <%= render @users%>
</div>

app/views/users/show.html.erb
<div id="user_details_container">
  <%= render @user %>
  <div id="user_bio">
    <h4>Bio</h4>
    <p>
      Lorem ipsum dolor sit amet, 
      consectetur adipiscing elit, 
      sed do eiusmod tempor incididunt ut 
      labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco 
      laboris nisi ut aliquip ex ea commodo consequat.
    </p>
  </div>
  <% @user.last_three_posts.each do |post|%>
    <div id="users_id">
      <h3>Post #<%= post.id %></h3>
      <p><%= post.text %></p>
      <h4>Comments <%= post.comments_counter %> likes: <%= post.likes_counter %></h4>
    </div>
  <% end %>
     <%= link_to  "New posts", new_user_post_path(@user) %>
  <div id="button_container">
  <%= link_to  "See all posts", user_posts_path(@user.id) %>
  </div>
</div>